---
title: "Data Manipulation with dplyr"
author: "Rae Spriggs"
date: "2022-09-22"
output: github_document
---

Once you've imported data, you're going to need to do some cleaning up. 

```{r}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = 6, 
  out.width = "90%"
)
```

```{r}
library(tidyverse)
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

## Ways to select variables / certain data

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

Select variables in order left to right on the tibble
```{r}
select(litters_data, group:gd_of_birth)
```

Select by telling it to remove certain variables
```{r}
select(litters_data, -pups_survive)

select(litters_data, -pups_survive, -group)
```

## Ways to rename variables 
 
```{r}
select(litters_data, GROUP = group, LITTER_NUMBER = litter_number)

##OR - another way to do the same thing

rename(litters_data, GROUP = group, LITTER_NUMBER = litter_number)
```

## Helper functions (starts with, ends with, and contains)

```{r}
select(litters_data, starts_with("gd"))
```

```{r}
select(litters_data, litter_number, pups_survive, everything())
```

```{r}
relocate(litters_data, litter_number, pups_survive)
```

