---
title: "Tidying Data"
author: "Rae Spriggs"
date: "2022-09-27"
output: github_document
---

```{r}
library(tidyverse)

options(tibble.print_min = 5)
```

Key functions for tidying data 
Using libraries tidyr and dplyr 

tidying single tables: 
pivot_longer 
separate

untidying single tables: 
pivot_wider 

combining multiple tables: 
bind_rows
*_join (left, right, full or inner)

```{r}
pulse_df = haven:: read_sas ('data/public_pulse_data.sas7bdat') %>% 
  janitor:: clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = 'visit', 
    values_to = 'bdi',
    names_prefix = 'bdi_score_' 
  ) %>% 
  
  mutate(
    visit = replace(visit, visit == 'bl', '00m'), 
    visit = factor(visit)
  ) %>% 
  
  arrange(id, visit)

```

## Learning assessment
```{r, learning assessment}

litters_df = read_csv('data/FAS_litters.csv') %>% 
  janitor::clean_names() %>% 
  select(litter_number, ends_with("weight")) %>% 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight") %>% 
    mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
  
view(litters_df)
```

## Pivot wider 
```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

analysis_results_wide = pivot_wider(
  analysis_result, 
  names_from = 'time', 
  values_from = 'mean'
)
```

## Binding rows 
```{r}
fellowship_ring = readxl:: read_excel('data/LoTR_Words.xlsx', range = 'B3:D6') %>% 
  mutate(movie = 'fellowship_ring')

two_towers = readxl:: read_excel('data/LoTR_Words.xlsx', range = 'F3:H6') %>% 
  mutate(movie = 'two_towers')

return_king = readxl:: read_excel('data/LoTR_Words.xlsx', range = 'J3:L6') %>% 
  mutate(movie = 'return_king')

lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor:: clean_names() %>% 
  pivot_longer(
    female:male, 
    names_to = 'gender',
    values_to = 'words'
  ) %>% 
  
  mutate(race = str_to_lower(race))
```

```{r}
pups = 
  read_csv('data/FAS_pups.csv') %>% 
  janitor:: clean_names() %>% 
  mutate(sex = recode(sex, `1` = 'male', `2` = 'female'), 
  sex = factor(sex))

litter = 
  read_csv("data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))

fas_data = 
  left_join(pups, litter, by = "litter_number")

view(fas_data)

```

